language: java
cache:
  directories:
  - $HOME/.m2
before_install:
- bash deployment/decrypt.bash
install: true
script: >
  mvn clean verify
  --file pom.xml
  --batch-mode
  --activate-profiles analyze
deploy:
  provider: script
  on:
    tags: true
  script: bash deployment/deploy.bash
env:
  global:
  - SONATYPE_USERNAME=vandmo
  - secure: "RFNO+4XcEuTtX3uVR7a3mYchUr8HwDk0CmvLC5WRKp+qs4JbzlPxQIAlCO/lMlY7uzbAFRNcD9ZfXDNCb9umcvQI9M90yhooIDe4wohfg1hxLiyNu+gzgLif/ApI6byhRXwBa9wn/AXKypZLpxyQ2wjZOCGB2vMwAz8Mu+9E/HJBNckYz81ULEaqjT1HEpzkpHoFoKwmFue+xjwrF25iP2ViWnkevAxXFAC1mqPzFF8fwrVSdGa08PCLg3p84edyOycW2cpZsLwtv9xnKuWyGjTnSl6qCdRwW3wy8jio8fNiVKdK9AzghIRu/COgSaNIcnWht9VoZsGhwqdp04v9cioD459ZpcX2HHPnYRI6Ov3BgEhoh+6LI0kEsmDsaFOhOqhcM9evIWzVjYI4YHyzbTR1PnvR30r0okfHeaX9TEGFojuPJrJT7hKSPl0043TWv2Q6qx2hXKpzuyUbpg9t1K0uJWSI3MKZX6y+6pYhYwxNhchQIUFFLN43bu3appLsPXQqd3PHEc8/mxQijTVOEDm7tOOQ/cfVwpHZjwJ+xrktLzJCEOcP8OyHXgX8uHD10t1PoDIxBoGT6T6Gp+Ypls4gfe0vDyOwsariUYX9pYBAIomMGWTKEdW8hZ+DNxV0/3LAnMKQoSCBgE/YEaaOL0qoK0G2iHdDts2gy40J26U="
  - secure: "SXXoDGbSL7614QlbIPhVNYKrnw7F4Q0O/kg68Do1D2aOC3cbXNmp10LR8O6+SLdatUkXVeUunB4P8JgvkCNqulpMjthtCfyNX9VD+mkUM4cqAwd4N4T5FPmsx36DOeW8T5uTcPOHUpogg5Oiyg42RrPn9L+8aHYvwu5wgghCsgNnIXJB4BpNhHPc6O6pLQ6/Ej08Fwmla+blMcv5bc0XnGi7SZ6xQq6OgMg6e15IO1Szm3lEmlOCOHuS7OHVnOJUQmqa8M/mjGc9JHHV6NwXh/uhfpwhmw74eNC+yUaV6qcrX/Pn0CPHkp2f/D5UNKbgfcL6ddzkTXfcHt4obNlW1CfyZRFfm+iM8cyV7tcUIKeLFGG5LMXGdfp6LJoV9UI6N3D0z2PRKu3rf8LjHqs9CVlwMTEp8qEBytFnlWOWWXRUUj2SGuHdN/QiWg3uWYEh9OcdnHNN/3chrGF/2E+xCNSveuts1pBY0M2TdkmtkM2j3ZWHAlcFdtIVYAvxS8/SkOdx3AirCrsShZ2DyU7tu6xr5f9JzZ48GEYNkkXkHgSTeQ4bZ5t7H/cD4Sibw2LqaHn2EfhXeWwQSotcl66SX2muJTAuNLOJuXFGcLCB1nH7FPIRPWsrRydafeH/SZRX4/0sLdrZy3gXwiRINEeWPFZbLV9Egk6fN6pddWjshMY="

