language: java
cache:
  directories:
  - $HOME/.m2
before_install:
- bash deployment/decrypt.bash
install: true
script: >
  mvn clean verify
  --file pom.xml
  --batch-mode
  --activate-profiles analyze
deploy:
  provider: script
  on:
    tags: true
  script: bash deployment/deploy.bash
env:
  global:
  - SONATYPE_USERNAME=vandmo
  - secure: FYVj0pwCmLdpD9xxaULd5tTVieP/bvLlDvVxcw+pzOWNJFmsYuPA7+ITjlZjQa/eQRZ0MBOSf/OYIUFPTUPy3hBbwwjWkxtzwOk47w1DbTlWPF8q9m9HzL06/ODJ2yXKGMlaYz7PAPBMieqBecYqSC0+jhYE3SRkttTZb4pQsQet0mDPgiVbBQ+JGdt9xFCRj0bvfeow1pQMp4FcqrtRGH8hdyH1pTLoSSjtE56hIBB0TS98WnFlO26COD0jaG0fJ138lP7KOfrAiZnNhykZCvTvmQE+YCsBmwItyvi9XwF+ovJQc74JfS1U+mpCq97k9I+1qV8+3JSSUU0X44RVt90dWjMaqE8vSpw5qkXD1EXzjJpI4c1kaDc/uTu07yXjk0GytEMcT30C7KGVeqAHghdMfVe9iTqJ/O0dhtSx84PM/Vj756eMkScdDAFG4yh/G/jfu1tszSZHkik0OpFuf4TGQ3ULiqHnlwwGRtdAAhjnOjv4hW86gxery+BAVNy1+jN1JALQ63Hzv1CEZ2i3XbijLiS3/ltIaYSsgpNyK6K7ZgM9zeNx0EesSXv+pGB1sgf6oCBHLMTv18yw4QzzFsKPfDxZtsxo0K8LRZ7hCRpukuvV4+5l8FuxoEXgqBSBfluJGEUCHCYZQ+PHdi46EjqNvt6wggysKWLJdE3b+1I=
  - secure: EVXrU16TZVpC/j8EdggRYi4+DhdOen91kyDKzBDbBQX55oxFGbvoQojLFKJjkf/AEuhRfZGLE6RQuv03+MULG23eE+vYsKpfh3Q6CunHRwvxNNku+zeuoOy8hYNGHYn1KL4IsShrqm0ySeLzRSDxNGFZCMIRC2lvCDri7gy1wGMMZZIDWtv2oPvdoEQIzqJV0SvAKLt0MD18up+Q3MWCtPkXIRtACCDGPFIk7bz3uVM5FdMceE9OTYZV9YmJARR4m8heqeGFkwJg2p8OIa2btGyzDfXn/b2p3wPMV2MAjVnLWq3cBGj2apLbjmHKgrIsdwmB//K6KVf7ODih89I/jH7YJb5dZ5c2LD8mXT9Kwh85gp6dktTbYMoJ1Z3matAt/YT8PXiC7RRNnNCbyHn9F5b6kBHBBuF3R5L6y3e0AWhbBLtxt7MWNCsBRzSWS8WGfXf810OnJziedCO+6E0zeWHiry/DIrvM8XgdRcODq/Py20f2XD9wwyETbz44y9UCG1zhwfSd+ut3RHlumMktHnbu/sF6aiDCm3Oftc0TYvyKBdyhoVJLopFRLQCLoz/DVk1E62R91B4zO6PBiK8PJEt7jWKhS2QbFdp03Hlr/hxjIkofjF3fkKh3bLOIY29H1piw//guHZiclLKUvjwabAHZLtarEsG97maHOR73sLs=
