language: java
jdk: openjdk8
cache:
  directories:
  - $HOME/.m2
install: true
script: tasks/build
deploy:
  provider: script
  on:
    tags: true
  script: tasks/deploy
env:
  global:
  - SONATYPE_USERNAME=vandmo

